/**
 * AI Assistant routes
 *
 * POST /api/ai/draft  — generate a personalised WhatsApp outreach message
 *   using live CRM context (tasks, proposals, WhatsApp history).
 *
 * LLM integration is OPTIONAL.  When OPENAI_API_KEY is present the response
 * is generated by gpt-4o-mini; otherwise an enriched template built from
 * real Supabase data is returned.  The endpoint never errors because a key
 * is missing — ai_powered:false signals the fallback path.
 */

import { Router } from "express";
import { supabase } from "../lib/supabase.js";

const router = Router();

// ── Types ─────────────────────────────────────────────────────────────────────

interface LeadPayload {
  id: number;
  name: string;
  email: string;
  phone: string;
  status: string;
  source: string;
}

interface CrmContext {
  openTasks:      Array<{ note: string; follow_up_date: string }>;
  proposals:      Array<{ proposal_number: string; total: number; status: string }>;
  recentMessages: Array<{ body: string; direction: string }>;
}

// ── Enriched template (no LLM required) ───────────────────────────────────────

const SOURCE_INTEREST: Record<string, string> = {
  IndiaMart:      "bulk procurement or B2B solutions",
  WhatsApp:       "our offerings",
  Website:        "our services",
  JustDial:       "local business solutions",
  "Social Media": "our latest products",
};

function buildTemplateMessage(lead: LeadPayload, ctx: CrmContext): string {
  const lines: string[] = [`Hi ${lead.name}! 👋`, ``];

  // Contextual opener — prioritise richest data
  if (ctx.recentMessages.length > 0) {
    lines.push(
      `Following up on our recent WhatsApp conversation — I wanted to make sure all your questions were answered and see how we can move forward together.`,
    );
  } else if (ctx.proposals.length > 0) {
    const p = ctx.proposals[0];
    lines.push(
      `I'm following up on Proposal ${p.proposal_number} (${p.status}) that we shared with you. I'd love to hear your thoughts and address any questions you might have.`,
    );
  } else if (ctx.openTasks.length > 0) {
    const t = ctx.openTasks[0];
    const noteSnippet = t.note ? ` regarding: "${t.note}"` : "";
    lines.push(
      `I have a follow-up scheduled with you${noteSnippet} and wanted to connect before ${t.follow_up_date}.`,
    );
  } else {
    const interest = SOURCE_INTEREST[lead.source] ?? "our services";
    lines.push(
      `I noticed you reached out via ${lead.source} about ${interest}. I'd love to learn more about your requirements and see how we can help.`,
    );
  }

  lines.push(``);
  lines.push(
    `Our team has helped many clients achieve great results, and I'd love to personalise a solution just for you. 🎯`,
  );
  lines.push(``);
  lines.push(
    `Could we set up a quick 10-minute call this week? Just reply "Yes" and I'll send you a calendar link right away!`,
  );
  lines.push(``);
  lines.push(`Looking forward to connecting!`);
  lines.push(`— CRM Pro Team`);

  return lines.join("\n");
}

// ── POST /api/ai/draft ────────────────────────────────────────────────────────

router.post("/ai/draft", async (req, res) => {
  const { lead } = req.body as { lead?: LeadPayload };

  if (!lead?.id || !lead?.name) {
    res.status(400).json({ error: "lead.id and lead.name are required" });
    return;
  }

  // ── Fetch CRM context in parallel ─────────────────────────────────────────
  // Wrapped in try-catch so a Supabase initialisation failure (e.g. Node 20
  // missing native WebSocket) never crashes the route — we fall back to the
  // template with empty context instead.
  const digitsOnly = lead.phone.replace(/\D/g, "");

  let openTasks:      CrmContext["openTasks"]      = [];
  let proposals:      CrmContext["proposals"]      = [];
  let recentMessages: CrmContext["recentMessages"] = [];

  try {
    const [tasksRes, proposalsRes, convRes] = await Promise.all([
      supabase
        .from("tasks")
        .select("note, follow_up_date")
        .eq("lead_id", lead.id)
        .eq("done", false)
        .order("follow_up_date", { ascending: true })
        .limit(3),

      supabase
        .from("proposals")
        .select("proposal_number, total, status")
        .eq("lead_id", lead.id)
        .order("created_at", { ascending: false })
        .limit(3),

      supabase
        .from("whatsapp_conversations")
        .select("id")
        .eq("contact_phone", digitsOnly)
        .limit(1),
    ]);

    openTasks  = (tasksRes.data   ?? []) as CrmContext["openTasks"];
    proposals  = (proposalsRes.data ?? []) as CrmContext["proposals"];

    if (convRes.data && convRes.data.length > 0) {
      const convId = (convRes.data[0] as { id: string }).id;
      const msgsRes = await supabase
        .from("whatsapp_messages")
        .select("body, direction")
        .eq("conversation_id", convId)
        .order("created_at", { ascending: false })
        .limit(5);
      recentMessages = (msgsRes.data ?? []) as CrmContext["recentMessages"];
    }
  } catch (err) {
    console.warn("[ai/draft] CRM context fetch failed, using empty context:", (err as Error).message);
  }

  const ctx: CrmContext = { openTasks, proposals, recentMessages };

  // ── LLM path — only when OPENAI_API_KEY is configured ─────────────────────
  // Uses fetch directly so no npm package is required; the AI module is fully
  // optional and the server builds/runs without any key present.
  const openaiKey = process.env["OPENAI_API_KEY"];

  if (openaiKey) {
    try {
      const systemPrompt =
        "You are a professional CRM sales assistant. Write a short, warm WhatsApp outreach message for a sales rep to review and send. " +
        "Be concise (under 120 words), friendly, and personalised using the CRM context provided. " +
        "Do not use markdown. Output plain text only.";

      const contextLines = [
        `Lead: ${lead.name} | Source: ${lead.source} | Status: ${lead.status}`,
        openTasks.length
          ? `Open tasks: ${openTasks.map((t) => t.note || `follow-up by ${t.follow_up_date}`).join("; ")}`
          : "",
        proposals.length
          ? `Proposals: ${proposals.map((p) => `${p.proposal_number} (${p.status}, ₹${p.total.toLocaleString()})`).join("; ")}`
          : "",
        recentMessages.length
          ? `Recent WhatsApp: ${recentMessages
              .slice(0, 3)
              .map((m) => `[${m.direction}] ${m.body}`)
              .join(" | ")}`
          : "",
      ]
        .filter(Boolean)
        .join("\n");

      const openaiRes = await fetch("https://api.openai.com/v1/chat/completions", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${openaiKey}`,
        },
        body: JSON.stringify({
          model: "gpt-4o-mini",
          max_tokens: 300,
          messages: [
            { role: "system", content: systemPrompt },
            { role: "user",   content: contextLines },
          ],
        }),
      });

      if (openaiRes.ok) {
        const completion = await openaiRes.json() as {
          choices: Array<{ message: { content: string } }>;
        };
        const message =
          completion.choices[0]?.message?.content?.trim() ??
          buildTemplateMessage(lead, ctx);
        res.json({ message, ai_powered: true });
        return;
      }
    } catch (err) {
      // LLM call failed — fall through to template
      console.warn("[ai/draft] LLM call failed, falling back to template:", (err as Error).message);
    }
  }

  // ── Template fallback ─────────────────────────────────────────────────────
  const message = buildTemplateMessage(lead, ctx);
  res.json({ message, ai_powered: false });
});

export default router;
